kind: pipeline
name: dumpme-ui
type: docker
steps: 
  - 
    commands: 
      - yarn
    image: "node:alpine"
    name: deps
  - 
    commands: 
      - "yarn build"
    image: "node:alpine"
    name: build
  - 
    name: copyfiles
    image: appleboy/drone-scp
    settings:
      host:
        from_secret: HOST
      port: 22
      key:
        from_secret: SSH_KEY
      source: dist
      target: ~/apps/dumpme-ui
      username:
        from_secret: USER
      when:
        branch:
        - master
  -
    name: deploy
    image: appleboy/drone-ssh
    settings:
      settings:
      host:
        from_secret: HOST
      port: 22
      key:
        from_secret: SSH_KEY
      username:
        from_secret: USER
      script:
        bash ~/apps/dumpme-ui/deploy.sh
      when:
        branch:
        - master